#!/usr/bin/env bash

rm -rf .python_packages
mkdir -p .python_packages/lib

uv sync --no-dev --frozen --no-install-project
cp -r .venv/lib/python3.13/site-packages .python_packages/lib/

# files auto-generated by uv
rm .python_packages/lib/site-packages/_virtualenv.pth
rm .python_packages/lib/site-packages/_virtualenv.py

source .venv/bin/activate
find . -type d -name __pycache__ -exec rm -rf {} &>/dev/null \;
func azure functionapp publish eduardoteste --no-build
